// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZllLZRyOYeerAlF9jKXN7j1CifGGbps8',
    appId: '1:46411859425:web:12691ff79172caf65dfea0',
    messagingSenderId: '46411859425',
    projectId: 'flutter-chat-app-a1579',
    authDomain: 'flutter-chat-app-a1579.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a1579.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYZEIGOJB_UWnPR28rHUwgHlMihMPRfY',
    appId: '1:46411859425:android:aa2b28d11e4757875dfea0',
    messagingSenderId: '46411859425',
    projectId: 'flutter-chat-app-a1579',
    storageBucket: 'flutter-chat-app-a1579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvimPJUTvxrnHBEshDASXQ7JCZgh_b704',
    appId: '1:46411859425:ios:48c550b590a831625dfea0',
    messagingSenderId: '46411859425',
    projectId: 'flutter-chat-app-a1579',
    storageBucket: 'flutter-chat-app-a1579.appspot.com',
    iosClientId: '46411859425-q0jt6lap04damgrduce6cj838cf36c1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvimPJUTvxrnHBEshDASXQ7JCZgh_b704',
    appId: '1:46411859425:ios:c35050300057666d5dfea0',
    messagingSenderId: '46411859425',
    projectId: 'flutter-chat-app-a1579',
    storageBucket: 'flutter-chat-app-a1579.appspot.com',
    iosClientId: '46411859425-er2a3r9enop2tahbhfugd27at4vjnept.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
